service: py-example6-sqs-post
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: default
  region: eu-central-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "sqs:*"
          Resource: "*" 

functions:
  sqspost:
    handler: handler.lambda_handler
